### ISSUE TITLE
Inconsistent treatment of increasing functions. 

### ISSUE THREAD

**Issue by rmbzz** [arechnitzer/CLP1#28]
This comment refers to the version of CLP1 dated 26 August 2022 which is posted at personal.math.ubc.ca

In Corollary 2.13.12, a result is given for increasing functions with non-strict inequalities. 
If f'(c) \geq 0, the  f(b) \geq f(a) when b > a. 

This result is restated in section 3.6.2 with strict inequalities: 
if f'(x) >0, then  f(b) > f(a) when b>a. 

I think the formulation from section 3.6.2 is more common in textbooks at this level, but the authors probably know better than I which one fits best with the rest of the book. 

(And we are well into our second semester with the text at Kentucky and it seems to be going fairly smoothly. Thanks.) 

Russell Brown

**Comment by joelfeldman** [comment]
A fix has been implemented.
